### ISSUE TITLE
Just getting 100 records

### ISSUE THREAD

**Issue by ghost** [rjpower/openfda-R#8]
Hi,

```
library("openfda")
get_data = fda_query("/drug/event.json") %>%
  fda_api_key("qEr7aWQ6dAtyi7y5Hgl26tYee1f3YzmdhsGvslEC") %>%
  fda_count("patient.patientweight") %>% 
  fda_exec()
```
I'm always getting a maximum of 100 lines in R?

**Comment by ledell** [comment]
@rainmain You probably realized this (and why you closed your ticket), but that's probably the API limit per call.  I don't know this package well enough to say if it supports this, but it's common to have a function that will keep making calls on your behalf if there are still records remaining that match your query.
